//go:build js

/*
 * Copyright (c) 2021 The XGo Authors (xgo.dev). All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*------------------------------------------------------------------------------
//   This code was generated by template callbacks.go.tmpl.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "callbacks.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/
// Code generated by spx codegen; DO NOT EDIT.

package webffi

import (
	"syscall/js"
)

// 预先缓存 JavaScript 事件名，分发时无需反复创建 Go 字符串。
// js.Value.Equal 使用 JavaScript 的 === 比较已驻留字符串，可避免 Go 堆分配。
var (
	jsEventOnEngineStart             = js.ValueOf("OnEngineStart")
	jsEventOnEngineUpdate            = js.ValueOf("OnEngineUpdate")
	jsEventOnEngineFixedUpdate       = js.ValueOf("OnEngineFixedUpdate")
	jsEventOnEngineDestroy           = js.ValueOf("OnEngineDestroy")
	jsEventOnEngineDestroyed         = js.ValueOf("OnEngineDestroyed")
	jsEventOnEngineReset             = js.ValueOf("OnEngineReset")
	jsEventOnEnginePause             = js.ValueOf("OnEnginePause")
	jsEventOnSceneSpriteInstantiated = js.ValueOf("OnSceneSpriteInstantiated")
	jsEventOnSpriteReady             = js.ValueOf("OnSpriteReady")
	jsEventOnSpriteUpdated           = js.ValueOf("OnSpriteUpdated")
	jsEventOnSpriteFixedUpdated      = js.ValueOf("OnSpriteFixedUpdated")
	jsEventOnSpriteDestroyed         = js.ValueOf("OnSpriteDestroyed")
	jsEventOnSpriteFramesSetChanged  = js.ValueOf("OnSpriteFramesSetChanged")
	jsEventOnSpriteAnimationChanged  = js.ValueOf("OnSpriteAnimationChanged")
	jsEventOnSpriteFrameChanged      = js.ValueOf("OnSpriteFrameChanged")
	jsEventOnSpriteAnimationLooped   = js.ValueOf("OnSpriteAnimationLooped")
	jsEventOnSpriteAnimationFinished = js.ValueOf("OnSpriteAnimationFinished")
	jsEventOnSpriteVfxFinished       = js.ValueOf("OnSpriteVfxFinished")
	jsEventOnSpriteScreenExited      = js.ValueOf("OnSpriteScreenExited")
	jsEventOnSpriteScreenEntered     = js.ValueOf("OnSpriteScreenEntered")
	jsEventOnMousePressed            = js.ValueOf("OnMousePressed")
	jsEventOnMouseReleased           = js.ValueOf("OnMouseReleased")
	jsEventOnKeyPressed              = js.ValueOf("OnKeyPressed")
	jsEventOnKeyReleased             = js.ValueOf("OnKeyReleased")
	jsEventOnActionPressed           = js.ValueOf("OnActionPressed")
	jsEventOnActionJustPressed       = js.ValueOf("OnActionJustPressed")
	jsEventOnActionJustReleased      = js.ValueOf("OnActionJustReleased")
	jsEventOnAxisChanged             = js.ValueOf("OnAxisChanged")
	jsEventOnCollisionEnter          = js.ValueOf("OnCollisionEnter")
	jsEventOnCollisionStay           = js.ValueOf("OnCollisionStay")
	jsEventOnCollisionExit           = js.ValueOf("OnCollisionExit")
	jsEventOnTriggerEnter            = js.ValueOf("OnTriggerEnter")
	jsEventOnTriggerStay             = js.ValueOf("OnTriggerStay")
	jsEventOnTriggerExit             = js.ValueOf("OnTriggerExit")
	jsEventOnUiReady                 = js.ValueOf("OnUiReady")
	jsEventOnUiUpdated               = js.ValueOf("OnUiUpdated")
	jsEventOnUiDestroyed             = js.ValueOf("OnUiDestroyed")
	jsEventOnUiPressed               = js.ValueOf("OnUiPressed")
	jsEventOnUiReleased              = js.ValueOf("OnUiReleased")
	jsEventOnUiHovered               = js.ValueOf("OnUiHovered")
	jsEventOnUiClicked               = js.ValueOf("OnUiClicked")
	jsEventOnUiToggle                = js.ValueOf("OnUiToggle")
	jsEventOnUiTextChanged           = js.ValueOf("OnUiTextChanged")
)

// gdspxDispatch 是 Web 平台所有 Godot -> Go 事件的统一分发入口。
//
// 调用时机：Godot 产生引擎、精灵、输入、物理或 UI 事件时。
// 直接上级：library_godot_gdspx.js 通过 FFI.gdspx_dispatch 调用。
// 最顶层来源：Godot 主循环、输入系统、物理系统或节点信号。
// 跨模块去向：根据 args[0] 的事件名调用 webffi.BindCallback() 保存的 callbacks.OnXxx。
// js.Value.Equal 直接比较 JavaScript 值，避免为事件名创建 Go 字符串。
func gdspxDispatch(this js.Value, args []js.Value) any {
	if len(args) == 0 {
		return nil
	}
	eventVal := args[0]
	if eventVal.Equal(jsEventOnEngineStart) {
		contactEventGeneration++
		if callbacks.OnEngineStart == nil {
			return nil
		}
		callbacks.OnEngineStart()
	} else if eventVal.Equal(jsEventOnEngineUpdate) {
		SyncWebInputSnapshot()
		if callbacks.OnEngineUpdate == nil {
			return nil
		}
		arg0 := JsToGdFloat(args[1])
		callbacks.OnEngineUpdate(arg0)
	} else if eventVal.Equal(jsEventOnEngineFixedUpdate) {
		SyncWebInputSnapshot()
		if callbacks.OnEngineFixedUpdate == nil {
			return nil
		}
		arg0 := JsToGdFloat(args[1])
		callbacks.OnEngineFixedUpdate(arg0)
	} else if eventVal.Equal(jsEventOnEngineDestroy) {
		contactEventGeneration++
		if callbacks.OnEngineDestroy == nil {
			return nil
		}
		callbacks.OnEngineDestroy()
	} else if eventVal.Equal(jsEventOnEngineDestroyed) {
		if callbacks.OnEngineDestroyed == nil {
			return nil
		}
		callbacks.OnEngineDestroyed()
	} else if eventVal.Equal(jsEventOnEngineReset) {
		contactEventGeneration++
		if callbacks.OnEngineReset == nil {
			return nil
		}
		callbacks.OnEngineReset()
	} else if eventVal.Equal(jsEventOnEnginePause) {
		if callbacks.OnEnginePause == nil {
			return nil
		}
		arg0 := JsToGdBool(args[1])
		callbacks.OnEnginePause(arg0)
	} else if eventVal.Equal(jsEventOnSceneSpriteInstantiated) {
		if callbacks.OnSceneSpriteInstantiated == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		arg1 := JsToGdString(args[2])
		callbacks.OnSceneSpriteInstantiated(arg0, arg1)
	} else if eventVal.Equal(jsEventOnSpriteReady) {
		if callbacks.OnSpriteReady == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		callbacks.OnSpriteReady(arg0)
	} else if eventVal.Equal(jsEventOnSpriteUpdated) {
		if callbacks.OnSpriteUpdated == nil {
			return nil
		}
		arg0 := JsToGdFloat(args[1])
		callbacks.OnSpriteUpdated(arg0)
	} else if eventVal.Equal(jsEventOnSpriteFixedUpdated) {
		if callbacks.OnSpriteFixedUpdated == nil {
			return nil
		}
		arg0 := JsToGdFloat(args[1])
		callbacks.OnSpriteFixedUpdated(arg0)
	} else if eventVal.Equal(jsEventOnSpriteDestroyed) {
		if callbacks.OnSpriteDestroyed == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		callbacks.OnSpriteDestroyed(arg0)
	} else if eventVal.Equal(jsEventOnSpriteFramesSetChanged) {
		if callbacks.OnSpriteFramesSetChanged == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		callbacks.OnSpriteFramesSetChanged(arg0)
	} else if eventVal.Equal(jsEventOnSpriteAnimationChanged) {
		if callbacks.OnSpriteAnimationChanged == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		callbacks.OnSpriteAnimationChanged(arg0)
	} else if eventVal.Equal(jsEventOnSpriteFrameChanged) {
		if callbacks.OnSpriteFrameChanged == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		callbacks.OnSpriteFrameChanged(arg0)
	} else if eventVal.Equal(jsEventOnSpriteAnimationLooped) {
		if callbacks.OnSpriteAnimationLooped == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		callbacks.OnSpriteAnimationLooped(arg0)
	} else if eventVal.Equal(jsEventOnSpriteAnimationFinished) {
		if callbacks.OnSpriteAnimationFinished == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		callbacks.OnSpriteAnimationFinished(arg0)
	} else if eventVal.Equal(jsEventOnSpriteVfxFinished) {
		if callbacks.OnSpriteVfxFinished == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		callbacks.OnSpriteVfxFinished(arg0)
	} else if eventVal.Equal(jsEventOnSpriteScreenExited) {
		if callbacks.OnSpriteScreenExited == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		callbacks.OnSpriteScreenExited(arg0)
	} else if eventVal.Equal(jsEventOnSpriteScreenEntered) {
		if callbacks.OnSpriteScreenEntered == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		callbacks.OnSpriteScreenEntered(arg0)
	} else if eventVal.Equal(jsEventOnMousePressed) {
		if callbacks.OnMousePressed == nil {
			return nil
		}
		arg0 := JsToGdInt(args[1])
		callbacks.OnMousePressed(arg0)
	} else if eventVal.Equal(jsEventOnMouseReleased) {
		if callbacks.OnMouseReleased == nil {
			return nil
		}
		arg0 := JsToGdInt(args[1])
		callbacks.OnMouseReleased(arg0)
	} else if eventVal.Equal(jsEventOnKeyPressed) {
		arg0 := JsToGdInt(args[1])
		RecordWebKeyState(arg0, true)
		if callbacks.OnKeyPressed == nil {
			return nil
		}
		callbacks.OnKeyPressed(arg0)
	} else if eventVal.Equal(jsEventOnKeyReleased) {
		arg0 := JsToGdInt(args[1])
		RecordWebKeyState(arg0, false)
		if callbacks.OnKeyReleased == nil {
			return nil
		}
		callbacks.OnKeyReleased(arg0)
	} else if eventVal.Equal(jsEventOnActionPressed) {
		if callbacks.OnActionPressed == nil {
			return nil
		}
		arg0 := JsToGdString(args[1])
		callbacks.OnActionPressed(arg0)
	} else if eventVal.Equal(jsEventOnActionJustPressed) {
		if callbacks.OnActionJustPressed == nil {
			return nil
		}
		arg0 := JsToGdString(args[1])
		callbacks.OnActionJustPressed(arg0)
	} else if eventVal.Equal(jsEventOnActionJustReleased) {
		if callbacks.OnActionJustReleased == nil {
			return nil
		}
		arg0 := JsToGdString(args[1])
		callbacks.OnActionJustReleased(arg0)
	} else if eventVal.Equal(jsEventOnAxisChanged) {
		if callbacks.OnAxisChanged == nil {
			return nil
		}
		arg0 := JsToGdString(args[1])
		arg1 := JsToGdFloat(args[2])
		callbacks.OnAxisChanged(arg0, arg1)
	} else if eventVal.Equal(jsEventOnCollisionEnter) {
		if callbacks.OnCollisionEnter == nil {
			return nil
		}
		arg0 := JsToGdInt(args[1])
		arg1 := JsToGdInt(args[2])
		callbacks.OnCollisionEnter(arg0, arg1)
	} else if eventVal.Equal(jsEventOnCollisionStay) {
		if callbacks.OnCollisionStay == nil {
			return nil
		}
		arg0 := JsToGdInt(args[1])
		arg1 := JsToGdInt(args[2])
		callbacks.OnCollisionStay(arg0, arg1)
	} else if eventVal.Equal(jsEventOnCollisionExit) {
		if callbacks.OnCollisionExit == nil {
			return nil
		}
		arg0 := JsToGdInt(args[1])
		arg1 := JsToGdInt(args[2])
		callbacks.OnCollisionExit(arg0, arg1)
	} else if eventVal.Equal(jsEventOnTriggerEnter) {
		if callbacks.OnTriggerEnter == nil {
			return nil
		}
		arg0 := JsToGdInt(args[1])
		arg1 := JsToGdInt(args[2])
		callbacks.OnTriggerEnter(arg0, arg1)
	} else if eventVal.Equal(jsEventOnTriggerStay) {
		if callbacks.OnTriggerStay == nil {
			return nil
		}
		arg0 := JsToGdInt(args[1])
		arg1 := JsToGdInt(args[2])
		callbacks.OnTriggerStay(arg0, arg1)
	} else if eventVal.Equal(jsEventOnTriggerExit) {
		if callbacks.OnTriggerExit == nil {
			return nil
		}
		arg0 := JsToGdInt(args[1])
		arg1 := JsToGdInt(args[2])
		callbacks.OnTriggerExit(arg0, arg1)
	} else if eventVal.Equal(jsEventOnUiReady) {
		if callbacks.OnUiReady == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		callbacks.OnUiReady(arg0)
	} else if eventVal.Equal(jsEventOnUiUpdated) {
		if callbacks.OnUiUpdated == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		callbacks.OnUiUpdated(arg0)
	} else if eventVal.Equal(jsEventOnUiDestroyed) {
		if callbacks.OnUiDestroyed == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		callbacks.OnUiDestroyed(arg0)
	} else if eventVal.Equal(jsEventOnUiPressed) {
		if callbacks.OnUiPressed == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		callbacks.OnUiPressed(arg0)
	} else if eventVal.Equal(jsEventOnUiReleased) {
		if callbacks.OnUiReleased == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		callbacks.OnUiReleased(arg0)
	} else if eventVal.Equal(jsEventOnUiHovered) {
		if callbacks.OnUiHovered == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		callbacks.OnUiHovered(arg0)
	} else if eventVal.Equal(jsEventOnUiClicked) {
		if callbacks.OnUiClicked == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		callbacks.OnUiClicked(arg0)
	} else if eventVal.Equal(jsEventOnUiToggle) {
		if callbacks.OnUiToggle == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		arg1 := JsToGdBool(args[2])
		callbacks.OnUiToggle(arg0, arg1)
	} else if eventVal.Equal(jsEventOnUiTextChanged) {
		if callbacks.OnUiTextChanged == nil {
			return nil
		}
		arg0 := JsToGdObj(args[1])
		arg1 := JsToGdString(args[2])
		callbacks.OnUiTextChanged(arg0, arg1)
	}
	return nil
}
